"""AI-powered care advisor using RAG over a curated pet care knowledge base.

Retrieves the most relevant snippets via Gemini embeddings (`gemini-embedding-001`
with task-type-aware encoding) stored in a persistent ChromaDB collection, then
asks Google Gemini to review the day's plan strictly against retrieved guidance
and return structured warnings the Scheduler can surface alongside its
rule-based output.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import numpy as np
from dotenv import load_dotenv

load_dotenv()

LOG_PATH = Path(__file__).parent / "pawpal.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.FileHandler(LOG_PATH),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger("pawpal.advisor")

ADVISOR_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
EMBEDDING_MODEL = os.getenv("GEMINI_EMBEDDING_MODEL", "gemini-embedding-001")
CHROMA_PATH = Path(__file__).parent / "knowledge" / ".chroma"
CHROMA_COLLECTION = "pawpal_snippets"
MAX_TASKS_IN_PROMPT = 50
TRANSIENT_RETRY_SECONDS = 2.0


@dataclass
class KnowledgeSnippet:
    source_id: str
    title: str
    content: str
    score: float = 0.0


@dataclass
class AdvisorIssue:
    severity: str
    pet_name: str
    task_name: str
    issue: str
    recommendation: str
    citations: List[str] = field(default_factory=list)


@dataclass
class ProposedChange:
    """A concrete edit the advisor wants the scheduler to apply to a task in
    the proposed daily plan, so the final plan shown to the owner reflects the
    retrieved guidance instead of just describing the mismatch alongside it.

    `task_index` is the 1-based position of the task in the numbered plan the
    model was shown. The scheduler uses it to resolve duplicate-named tasks
    unambiguously; falls back to (task_name, pet_name) match if missing."""
    pet_name: str
    task_name: str
    change_type: str  # "shorten" | "lengthen" | "reschedule" | "remove"
    reason: str
    task_index: Optional[int] = None
    new_duration_min: Optional[int] = None
    new_start_hhmm: Optional[str] = None
    citations: List[str] = field(default_factory=list)


@dataclass
class AdvisorReview:
    available: bool
    issues: List[AdvisorIssue] = field(default_factory=list)
    proposed_changes: List[ProposedChange] = field(default_factory=list)
    summary: str = ""
    retrieved_sources: List[str] = field(default_factory=list)
    error: Optional[str] = None
    latency_ms: int = 0


class CareAdvisor:
    """Retrieves pet care guidance and asks Gemini to critique a daily plan."""

    SYSTEM_PROMPT = """\
You are PawPal+'s veterinary scheduling reviewer. You review a daily pet care plan that was generated by a rules-based scheduler and flag issues a knowledgeable owner would catch.

Strict rules:
1. Base every claim on the KNOWLEDGE SNIPPETS provided in the user message. Do not invent veterinary advice from prior knowledge.
2. For each pet, first identify which specific category in the snippets applies to it (e.g., breed energy class, age group, life stage) and use that category's numbers. Do not apply a different category's targets to the pet, even if a snippet contains a generic 'flag as insufficient' sentence aimed at a different category.
3. Do not speculate about facts that are not stated in the plan or pet descriptions. The plan does not include weather, temperature, location, or owner context unless explicitly listed. If a snippet's caveat depends on a triggering condition (e.g., 'in hot weather', 'above 80°F', 'after a large meal'), only apply it when the plan or pet description states that condition. Do not raise hypothetical 'may be too long if it's hot' style issues.
4. Reconcile snippets before flagging duration. Before calling a walk or exercise too long or too short, compare its duration to the daily target for the pet's category. A duration at or below the daily target cannot also be 'too long'. State the numeric range and the planned duration in the issue text so the comparison is explicit (e.g., 'target 20–30 min/day, plan provides 10 min').
5. A duration or behavior that falls inside a snippet's stated range or matches its guidance is not an issue — do not raise it at any severity. Do not raise low-severity nudges of the form 'consider if optimal', 'might be more appropriate', 'worth considering if…', or 'could be improved'. Every issue, including low severity, must cite a specific snippet-stated rule the plan violates or falls outside of. If the plan is within range and meets the snippet's conditions, do not flag it.
6. Cite the snippet source_id in the 'citations' array of every issue. If no snippet supports a concern, do not raise it.
7. Severity must be one of: high (health risk), medium (welfare concern), low (best-practice nudge).
8. Be specific. Reference the exact task name and pet name.
9. If the plan looks fine given the retrieved snippets, return an empty issues list, an empty proposed_changes list, and a one-sentence summary.
10. For every issue with a concrete fix from a snippet you MUST emit a matching entry in proposed_changes so the scheduler can apply it before the plan is shown to the owner. The plan the owner follows should reflect the retrieved guidance, not just be described by it. In particular: if an issue identifies a quantitative deviation from a snippet target (e.g., 'plan provides 70 min, target is 20–30 min'), you MUST emit one or more proposed_changes that bring the plan back into the range — shorten the longest task, remove a redundant task, or distribute the change across multiple existing tasks as appropriate. Do not raise the issue without proposing the fix. There is NO add-task or split-task operation: proposed_changes can only modify or remove tasks that already exist in the PROPOSED DAILY PLAN. If a snippet recommends 'split exercise into two sessions' but only one such task is in the plan, describe the recommendation in the issue text — do NOT emit multiple proposed_changes targeting the same task_index as a workaround for adding a session (those changes combine into one modified task, not two). Use change_type:
   - 'shorten' or 'lengthen' for duration adjustments — set new_duration_min to an integer minute value within the snippet's stated range (e.g., for a 20–30 min target, prefer 25).
   - 'reschedule' for timing changes — set new_start_hhmm to a 24-hour 'HH:MM' string. Choose a time that does not overlap with any other scheduled task visible in the plan.
   - 'remove' to drop a task entirely — appropriate for clear health-risk cases or when removing a redundant task is the cleanest way to bring a daily total back into range.
   task_index is REQUIRED. Set it to the 1-based number that prefixes the target task in the PROPOSED DAILY PLAN. The scheduler uses task_index to disambiguate when multiple tasks share a name (e.g., two 'Morning walk' entries for the same pet) — without it, your edit may be applied to the wrong task. pet_name and task_name must also match the indexed task exactly. If you cannot identify a single specific task, do not propose the change. Every change must include citations.
11. Issues without a concrete fix (purely informational concerns, owner-discretion nudges with no quantitative target) belong in issues only, not proposed_changes.
12. The summary must accurately describe what you actually emitted. Do not use past-tense action language ('has been shortened', 'was rescheduled', 'was removed', 'one of the walks has been shortened') in the summary unless you also emitted a matching proposed_changes entry. If proposed_changes is empty, the summary describes the plan's status and any concerns — never claim an action that was not requested in the structured output.
13. Do not contradict your own summary. If anywhere in your output you describe the plan as 'within target', 'within the target range', 'in range', 'adequate', 'fine', 'meets the recommendation', or any equivalent phrase, your proposed_changes MUST be empty — you cannot acknowledge the plan is in-range and then edit it anyway. Likewise, if you raise a concern about 'splitting into sessions' or 'adding a second walk', that is a recommendation for the owner only — describe it in the issue text and stop. Do not emit proposed_changes that pretend to add or split tasks; the scheduler has no operation for that and the change will be rejected.
"""

    OUTPUT_SCHEMA = {
        "type": "object",
        "properties": {
            "issues": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "severity": {
                            "type": "string",
                            "enum": ["high", "medium", "low"],
                        },
                        "pet_name": {"type": "string"},
                        "task_name": {"type": "string"},
                        "issue": {"type": "string"},
                        "recommendation": {"type": "string"},
                        "citations": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                    "required": [
                        "severity",
                        "pet_name",
                        "task_name",
                        "issue",
                        "recommendation",
                        "citations",
                    ],
                },
            },
            "proposed_changes": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "task_index": {"type": "integer"},
                        "pet_name": {"type": "string"},
                        "task_name": {"type": "string"},
                        "change_type": {
                            "type": "string",
                            "enum": [
                                "shorten",
                                "lengthen",
                                "reschedule",
                                "remove",
                            ],
                        },
                        "new_duration_min": {"type": "integer"},
                        "new_start_hhmm": {"type": "string"},
                        "reason": {"type": "string"},
                        "citations": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                    "required": [
                        "task_index",
                        "pet_name",
                        "task_name",
                        "change_type",
                        "reason",
                        "citations",
                    ],
                },
            },
            "summary": {"type": "string"},
        },
        "required": ["issues", "proposed_changes", "summary"],
    }

    def __init__(self, knowledge_dir: Optional[Path] = None):
        self.knowledge_dir = knowledge_dir or Path(__file__).parent / "knowledge"
        self.snippets: List[KnowledgeSnippet] = self._load_snippets()
        self._collection = None  # chromadb collection (vector store)

        # Gemini client is required for embeddings (Groq doesn't offer them)
        # and is the default chat provider when GROQ_API_KEY is unset.
        self._client = None
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            logger.warning(
                "GEMINI_API_KEY not set — advisor will run in fallback mode."
            )
            return
        try:
            from google import genai

            self._client = genai.Client(api_key=api_key)
        except ImportError:
            logger.warning(
                "google-genai package not installed — advisor disabled."
            )
            return
        except Exception as exc:
            logger.exception("Failed to initialize Gemini client: %s", exc)
            return

        # Optional Groq client — when present, chat calls can be routed to
        # Groq while embeddings still use Gemini (Groq has no embedding API).
        # Useful as a fallback when Gemini's daily generate_content quota is
        # hit, since Groq's free tier has separate, much higher limits.
        self._groq_client = None
        groq_key = os.getenv("GROQ_API_KEY")
        if groq_key:
            try:
                from groq import Groq

                self._groq_client = Groq(api_key=groq_key)
                logger.info(
                    "Groq enabled for chat (%s); Gemini still used for embeddings",
                    GROQ_MODEL,
                )
            except ImportError:
                logger.warning(
                    "groq package not installed — pip install groq to enable"
                )
            except Exception as exc:
                logger.exception("Failed to initialize Groq client: %s", exc)

        # Chat provider selection — defaults to Groq when both are available
        # (since Groq has more generous free-tier limits) but the UI can flip
        # this at any point via set_chat_provider().
        if self._groq_client is not None:
            self._chat_provider = "groq"
        elif self._client is not None:
            self._chat_provider = "gemini"
        else:
            self._chat_provider = None

        if self.snippets:
            self._collection = self._sync_chroma_collection()

        chat_label = (
            f"groq:{GROQ_MODEL}"
            if self._chat_provider == "groq"
            else (f"gemini:{ADVISOR_MODEL}" if self._chat_provider == "gemini" else "none")
        )
        logger.info(
            "CareAdvisor initialized with %d snippets from %s; vector store %s; chat=%s",
            len(self.snippets),
            self.knowledge_dir,
            "loaded (chromadb)" if self._collection is not None else "unavailable",
            chat_label,
        )

    @property
    def is_available(self) -> bool:
        return (
            self._client is not None
            and bool(self.snippets)
            and self._collection is not None
        )

    @property
    def available_providers(self) -> List[str]:
        """List of chat providers the user can pick between, in display order."""
        out: List[str] = []
        if self._client is not None:
            out.append("gemini")
        if self._groq_client is not None:
            out.append("groq")
        return out

    @property
    def chat_provider(self) -> Optional[str]:
        """Currently selected chat provider — 'gemini', 'groq', or None."""
        return self._chat_provider

    def set_chat_provider(self, provider: str) -> None:
        """Switch which provider handles the chat call. Embeddings always
        stay on Gemini regardless. Raises if the requested provider's client
        was never initialized (e.g., asking for groq without GROQ_API_KEY)."""
        if provider == "gemini":
            if self._client is None:
                raise ValueError("Gemini client not initialized (missing GEMINI_API_KEY)")
        elif provider == "groq":
            if self._groq_client is None:
                raise ValueError("Groq client not initialized (missing GROQ_API_KEY or groq package)")
        else:
            raise ValueError(f"Unknown chat provider: {provider!r}")
        if self._chat_provider != provider:
            logger.info("Chat provider switched: %s -> %s", self._chat_provider, provider)
            self._chat_provider = provider

    def _load_snippets(self) -> List[KnowledgeSnippet]:
        if not self.knowledge_dir.exists():
            logger.error("Knowledge directory %s does not exist", self.knowledge_dir)
            return []
        loaded: List[KnowledgeSnippet] = []
        for path in sorted(self.knowledge_dir.glob("*.md")):
            text = path.read_text(encoding="utf-8").strip()
            if not text:
                continue
            first_line = text.splitlines()[0].lstrip("# ").strip()
            loaded.append(
                KnowledgeSnippet(
                    source_id=path.stem,
                    title=first_line or path.stem,
                    content=text,
                )
            )
        return loaded

    def _embed_texts(self, texts: List[str], task_type: str) -> np.ndarray:
        """Embed a list of texts and return an L2-normalized (n, dim) matrix.
        Normalizing once means cosine similarity reduces to a plain dot product."""
        result = self._client.models.embed_content(
            model=EMBEDDING_MODEL,
            contents=texts,
            config={"task_type": task_type},
        )
        vectors = np.array(
            [e.values for e in result.embeddings], dtype=np.float32
        )
        norms = np.linalg.norm(vectors, axis=1, keepdims=True)
        return vectors / np.maximum(norms, 1e-12)

    def _sync_chroma_collection(self):
        """Open a persistent ChromaDB collection at CHROMA_PATH and upsert any
        snippet whose SHA1 content hash has changed since the last run.

        Embeddings are computed by Gemini (`gemini-embedding-001`) and stored
        in Chroma; the collection is configured for cosine similarity. Orphan
        entries (source files deleted from disk) are removed from the store.
        Returns the collection handle, or None if Chroma init fails."""
        try:
            import chromadb
        except ImportError:
            logger.warning(
                "chromadb package not installed — install with: pip install chromadb"
            )
            return None

        try:
            client = chromadb.PersistentClient(path=str(CHROMA_PATH))
            collection = client.get_or_create_collection(
                name=CHROMA_COLLECTION,
                metadata={
                    "hnsw:space": "cosine",
                    "embedding_model": EMBEDDING_MODEL,
                },
            )
        except Exception as exc:
            logger.exception("Failed to open ChromaDB collection: %s", exc)
            return None

        current_hashes = {
            s.source_id: hashlib.sha1(s.content.encode("utf-8")).hexdigest()
            for s in self.snippets
        }

        try:
            existing = collection.get(include=["metadatas"])
            existing_meta = {
                _id: (meta or {})
                for _id, meta in zip(
                    existing.get("ids") or [],
                    existing.get("metadatas") or [],
                )
            }
        except Exception as exc:
            logger.warning("Couldn't read existing Chroma entries: %s", exc)
            existing_meta = {}

        # Snippets needing (re-)embed: new, or content hash changed, or model changed.
        to_upsert = [
            s for s in self.snippets
            if existing_meta.get(s.source_id, {}).get("content_hash")
            != current_hashes[s.source_id]
            or existing_meta.get(s.source_id, {}).get("model") != EMBEDDING_MODEL
        ]

        # Orphans: entries in Chroma whose source markdown no longer exists.
        orphan_ids = [
            _id for _id in existing_meta if _id not in current_hashes
        ]
        if orphan_ids:
            try:
                collection.delete(ids=orphan_ids)
                logger.info(
                    "Removed %d orphan entry(ies) from Chroma: %s",
                    len(orphan_ids),
                    orphan_ids,
                )
            except Exception as exc:
                logger.warning("Failed to delete orphan Chroma entries: %s", exc)

        if not to_upsert:
            logger.info(
                "Chroma collection up to date (%d snippets, all hashes match)",
                len(self.snippets),
            )
            return collection

        try:
            embeddings = self._embed_texts(
                [s.content for s in to_upsert], "RETRIEVAL_DOCUMENT"
            )
        except Exception as exc:
            logger.exception("Failed to embed snippets for Chroma upsert: %s", exc)
            return None

        try:
            collection.upsert(
                ids=[s.source_id for s in to_upsert],
                documents=[s.content for s in to_upsert],
                embeddings=embeddings.tolist(),
                metadatas=[
                    {
                        "title": s.title,
                        "content_hash": current_hashes[s.source_id],
                        "model": EMBEDDING_MODEL,
                    }
                    for s in to_upsert
                ],
            )
            logger.info(
                "Upserted %d snippet(s) to Chroma (collection now holds %d total)",
                len(to_upsert),
                len(self.snippets),
            )
        except Exception as exc:
            logger.exception("Failed to upsert to Chroma: %s", exc)
            return None

        return collection

    def retrieve(self, query: str, k: int = 4) -> List[KnowledgeSnippet]:
        if not self.snippets or self._collection is None or self._client is None:
            return []
        try:
            query_vec = self._embed_texts([query], "RETRIEVAL_QUERY")[0]
        except Exception as exc:
            logger.exception("Failed to embed query: %s", exc)
            return []
        try:
            result = self._collection.query(
                query_embeddings=[query_vec.tolist()],
                n_results=min(k, len(self.snippets)),
                include=["documents", "metadatas", "distances"],
            )
        except Exception as exc:
            logger.exception("ChromaDB query failed: %s", exc)
            return []
        return self._snippets_from_chroma_result(result, idx=0)

    def _retrieve_for_pets(
        self,
        plan_lines: List[str],
        pet_descriptions: List[str],
        k_per_pet: int = 3,
        max_total: int = 8,
    ) -> List[KnowledgeSnippet]:
        """Retrieve snippets once per pet, then dedupe by source_id keeping the
        highest score so a senior cat's needs aren't drowned out by a puppy's
        plan lines in a single merged query. All pet queries are embedded in a
        single Gemini call and run through Chroma in a single batch query."""
        if not self.snippets or self._collection is None or self._client is None:
            return []
        if not pet_descriptions:
            return self.retrieve(" ".join(plan_lines), k=max_total)

        queries: List[str] = []
        for desc in pet_descriptions:
            pet_name = desc.split(",", 1)[0].strip()
            pet_lines = [ln for ln in plan_lines if f"for {pet_name}," in ln]
            queries.append(" ".join([desc] + (pet_lines or plan_lines)))

        try:
            query_vecs = self._embed_texts(queries, "RETRIEVAL_QUERY")
        except Exception as exc:
            logger.exception("Failed to embed pet queries: %s", exc)
            return []

        try:
            result = self._collection.query(
                query_embeddings=query_vecs.tolist(),
                n_results=min(k_per_pet, len(self.snippets)),
                include=["documents", "metadatas", "distances"],
            )
        except Exception as exc:
            logger.exception("ChromaDB per-pet query failed: %s", exc)
            return []

        best: dict[str, KnowledgeSnippet] = {}
        for query_idx in range(len(queries)):
            for snippet in self._snippets_from_chroma_result(result, idx=query_idx):
                existing = best.get(snippet.source_id)
                if existing is None or snippet.score > existing.score:
                    best[snippet.source_id] = snippet

        merged = sorted(best.values(), key=lambda s: s.score, reverse=True)
        return merged[:max_total]

    @staticmethod
    def _snippets_from_chroma_result(result: dict, idx: int) -> List[KnowledgeSnippet]:
        """Convert a single query's slice of a Chroma `query()` result into
        KnowledgeSnippet objects. Cosine distance is converted back to
        similarity (`1 - distance`); zero/negative similarities are dropped."""
        ids = (result.get("ids") or [[]])[idx] if idx < len(result.get("ids") or []) else []
        docs = (result.get("documents") or [[]])[idx] if idx < len(result.get("documents") or []) else []
        dists = (result.get("distances") or [[]])[idx] if idx < len(result.get("distances") or []) else []
        metas_outer = result.get("metadatas") or []
        metas = metas_outer[idx] if idx < len(metas_outer) else []
        snippets: List[KnowledgeSnippet] = []
        for source_id, doc, dist, meta in zip(ids, docs, dists, metas or [{}] * len(ids)):
            score = 1.0 - float(dist)
            if score <= 0:
                continue
            snippets.append(
                KnowledgeSnippet(
                    source_id=source_id,
                    title=(meta or {}).get("title", source_id),
                    content=doc,
                    score=score,
                )
            )
        return snippets

    def _call_chat(self, user_message: str):
        """Dispatch the advisor chat call to whichever provider is configured.

        Groq takes precedence when GROQ_API_KEY is set (used as a fallback
        when Gemini's daily generate_content quota is exhausted). Returns
        (raw_response_text, usage_dict). Embeddings always go through Gemini
        regardless of which provider handles chat — Groq has no embedding API.
        """
        if self._chat_provider == "groq":
            response = self._groq_client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user", "content": user_message},
                ],
                response_format={"type": "json_object"},
                temperature=0.2,
                max_tokens=4096,
            )
            text = response.choices[0].message.content or ""
            u = response.usage
            usage = (
                {
                    "prompt": u.prompt_tokens,
                    "output": u.completion_tokens,
                    "total": u.total_tokens,
                }
                if u is not None
                else {}
            )
            return text, usage

        config = {
            "system_instruction": self.SYSTEM_PROMPT,
            "response_mime_type": "application/json",
            "response_schema": self.OUTPUT_SCHEMA,
            "temperature": 0.2,
            "max_output_tokens": 4096,
        }
        response = self._client.models.generate_content(
            model=ADVISOR_MODEL,
            contents=user_message,
            config=config,
        )
        text = response.text or ""
        u = getattr(response, "usage_metadata", None)
        usage = (
            {
                "prompt": getattr(u, "prompt_token_count", 0) or 0,
                "output": getattr(u, "candidates_token_count", 0) or 0,
                "total": getattr(u, "total_token_count", 0) or 0,
            }
            if u is not None
            else {}
        )
        return text, usage

    def review_plan(
        self,
        plan_lines: List[str],
        pet_descriptions: List[str],
    ) -> AdvisorReview:
        """Retrieve relevant guidance and ask Claude to critique the plan."""
        if not plan_lines:
            return AdvisorReview(available=False, error="empty plan")

        if not self.is_available:
            return AdvisorReview(
                available=False,
                error="advisor unavailable (missing API key or knowledge base)",
            )

        plan_lines = plan_lines[:MAX_TASKS_IN_PROMPT]
        retrieved = self._retrieve_for_pets(plan_lines, pet_descriptions)
        if not retrieved:
            return AdvisorReview(
                available=False, error="no relevant knowledge snippets"
            )

        snippets_block = "\n\n".join(
            f"### source_id: {s.source_id}\n{s.content}" for s in retrieved
        )
        pets_block = "\n".join(f"- {desc}" for desc in pet_descriptions)
        # Number the plan lines so the model can refer to each task by a
        # 1-based task_index — the scheduler uses that index to apply edits
        # unambiguously even when two tasks share the same name.
        plan_block = "\n".join(
            f"{i}. {line}" for i, line in enumerate(plan_lines, start=1)
        )
        schema_str = json.dumps(self.OUTPUT_SCHEMA, indent=2)
        user_message = (
            "KNOWLEDGE SNIPPETS:\n"
            f"{snippets_block}\n\n"
            "PETS:\n"
            f"{pets_block}\n\n"
            "PROPOSED DAILY PLAN (each task is prefixed with its 1-based "
            "task_index — use that number in proposed_changes.task_index):\n"
            f"{plan_block}\n\n"
            "Review the plan against the snippets above and return JSON "
            "matching this schema (each issue citing one or more source_id "
            f"values):\n{schema_str}"
        )

        start = time.monotonic()
        text: Optional[str] = None
        usage: dict = {}
        last_exc: Optional[Exception] = None
        for attempt in (1, 2):
            try:
                text, usage = self._call_chat(user_message)
                break
            except Exception as exc:
                last_exc = exc
                msg = str(exc)
                transient = (
                    "503" in msg
                    or "UNAVAILABLE" in msg
                    or "RESOURCE_EXHAUSTED" in msg
                    or "429" in msg
                )
                if attempt == 1 and transient:
                    logger.warning(
                        "Chat transient error on attempt 1, retrying in %.1fs: %s",
                        TRANSIENT_RETRY_SECONDS,
                        exc,
                    )
                    time.sleep(TRANSIENT_RETRY_SECONDS)
                    continue
                latency_ms = int((time.monotonic() - start) * 1000)
                logger.exception(
                    "Advisor call failed in %dms: %s", latency_ms, exc
                )
                return AdvisorReview(
                    available=False,
                    error=f"{type(exc).__name__}: {exc}",
                    latency_ms=latency_ms,
                )
        if text is None:
            latency_ms = int((time.monotonic() - start) * 1000)
            return AdvisorReview(
                available=False,
                error=f"{type(last_exc).__name__}: {last_exc}"
                if last_exc
                else "advisor failed without response",
                latency_ms=latency_ms,
            )

        latency_ms = int((time.monotonic() - start) * 1000)
        if usage:
            logger.info(
                "Advisor call OK in %dms — prompt=%d output=%d total=%d",
                latency_ms,
                usage.get("prompt", 0),
                usage.get("output", 0),
                usage.get("total", 0),
            )
        else:
            logger.info("Advisor call OK in %dms", latency_ms)

        text = text.strip()
        if not text:
            return AdvisorReview(
                available=False,
                error="advisor returned empty response",
                latency_ms=latency_ms,
            )

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError as exc:
            logger.error("Failed to parse advisor JSON: %s", exc)
            return AdvisorReview(
                available=False,
                error=f"invalid JSON from advisor: {exc}",
                latency_ms=latency_ms,
            )

        issues = [
            AdvisorIssue(
                severity=item["severity"],
                pet_name=item["pet_name"],
                task_name=item["task_name"],
                issue=item["issue"],
                recommendation=item["recommendation"],
                citations=item.get("citations", []),
            )
            for item in parsed.get("issues", [])
        ]
        proposed_changes = [
            ProposedChange(
                pet_name=item["pet_name"],
                task_name=item["task_name"],
                change_type=item["change_type"],
                reason=item["reason"],
                task_index=item.get("task_index"),
                new_duration_min=item.get("new_duration_min"),
                new_start_hhmm=item.get("new_start_hhmm"),
                citations=item.get("citations", []),
            )
            for item in parsed.get("proposed_changes", [])
        ]
        return AdvisorReview(
            available=True,
            issues=issues,
            proposed_changes=proposed_changes,
            summary=parsed.get("summary", ""),
            retrieved_sources=[s.source_id for s in retrieved],
            latency_ms=latency_ms,
        )
